REM YOU MIGHT NEED TO UNCHECK COCOS2D MANUALLY
REM AS OF MAY 21ST 2021 IT DID NOT DOWNLOAD PROPERLY
C:\VsProLayoutVol02\vs_professional.exe --noweb  --add   ^
  --add Microsoft.VisualStudio.Workload.NetWeb   ^
  --add Microsoft.VisualStudio.Workload.ManagedGame   ^
  --add Microsoft.VisualStudio.Workload.Node   ^
  --add Microsoft.VisualStudio.Workload.Universal   ^
  --add Microsoft.VisualStudio.Workload.Azure   ^
  --add Microsoft.VisualStudio.Workload.NetCrossPlat   ^
  --add Microsoft.VisualStudio.Workload.NativeMobile   ^
  --add Component.GitHub.VisualStudio   ^
  --add Microsoft.Component.HelpViewer   ^
  --add Microsoft.VisualStudio.Component.ClassDesigner   ^
  --add Microsoft.VisualStudio.Component.Git   ^
  --add Microsoft.VisualStudio.Component.GraphDocument   ^
  --add Microsoft.VisualStudio.Component.LinqToSql --includeRecommended --includeOptional